version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    network_mode: "bridge"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
