// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	alert "github.com/henrique502/golang-clean/domain/alert"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AlertUpSert provides a mock function with given fields: _a0
func (_m *Repository) AlertUpSert(_a0 alert.Alert) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(alert.Alert) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
